openapi: "3.0.1"
info:
  version: "1.0.0"
  title: Simple Swagger API
servers:
  - url: http://example.com/v1
paths:
  /msg:
    get:
      responses:
        200:
          description: message
          content:
            application/json:
              schema:
                properties:
                  msgs:
                    type: array
                    items:
                      oneOf:
                        - $ref: '#/components/schemas/ImageMsg'
                        - $ref: '#/components/schemas/TextMsg'
                  msg:
                    oneOf:
                      - $ref: '#/components/schemas/ImageMsg'
                      - $ref: '#/components/schemas/TextMsg'
components:
  schemas:
    TextMsg:
      properties:
        id:
          type: integer
          example: 10555555
        text:
          type: string
          example: "hello world"
    ImageMsg:
      properties:
        id:
          type: integer
          example: 10444444
        img_url:
          type: string
          example: "https://example.com/foo.jpg"
