openapi: "3.0.1"
info:
  version: "1.0.0"
  title: Simple Swagger API
servers:
  - url: http://example.com/v1
paths:
  /hello:
    get:
      responses:
        200:
          description: 你好
          content:
            application/json:
              schema:
                properties:
                  hello:
                    $ref: '#/components/schemas/Hello'
components:
  schemas:
    Hello:
      properties:
        v_string:
          type: string
          example: world
        v_number:
          type: number
          example: 1.1
        v_integer:
          type: integer
          example: 10
        v_boolean:
          type: boolean
          example: false
        v_array:
          type: array
          items:
            type: string
        v_object:
          type: object
