openapi: "3.0.1"
info:
  version: "1.0.0"
  title: Simple Swagger API
servers:
  - url: http://example.com/v1
paths:
  /hello:
    get:
      parameters:
        - in: query
          name: id
          description: id
          schema:
            type: integer
            format: int32
          required: true
        - in: query
          name: time
          description: id
          schema:
            type: integer
            format: int32
          required: true
      responses:
        200:
          description: 你好
          content:
            application/json:
              schema:
                properties:
                  hello:
                    $ref: '#/components/schemas/Hello'
components:
  schemas:
    Hello:
      properties:
        name:
          type: string
          example: world
