openapi: "3.0.1"
info:
  version: "1.0.0"
  title: Simple Swagger API
servers:
  - url: http://example.com/v1
paths:
  /hello:
    get:
      responses:
        200:
          description: 你好
          content:
            application/json:
              schema:
                properties:
                  hello:
                    $ref: '#/components/schemas/Hello'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hello'
      responses:
        200:
          description: 你好的回复
          content:
            application/json:
              schema:
                properties:
                  hello:
                    $ref: '#/components/schemas/Hello'
components:
  schemas:
    Hello:
      properties:
        name:
          type: string
          example: world
