openapi: "3.0.1"
info:
  version: "1.0.0"
  title: Simple Swagger API
servers:
  - url: http://example.com/v1
paths:
  /hello:
    get:
      responses:
        200:
          description: 你好
          content:
            application/json:
              schema:
                properties:
                  foo:
                    $ref: '#/components/schemas/Foo'
                  bar:
                    $ref: '#/components/schemas/Bar'
components:
  schemas:
    Foo:
      properties:
        name:
          type: string
          enum:
            - a
            - b
            - c
        kind:
          type: integer
          enum:
            - 1
            - 2
            - 3
    Bar:
      properties:
        baz:
          $ref: '#/components/schemas/Baz'
    Baz:
      type: integer
      enum:
        - 1
        - 2
        - 3
