openapi: "3.0.1"
info:
  version: "1.0.0"
  title: Simple Swagger API
servers:
  - url: http://example.com/v1
paths:
  /hello:
    get:
      responses:
        200:
          description: 你好
          content:
            application/json:
              schema:
                properties:
                  hello:
                    $ref: '#/components/schemas/Hello'
components:
  schemas:
    Hello:
      properties:
        name:
          type: string
          enum:
            - foo
            - bar
            - baz
        kind:
          type: integer
          enum:
            - 1
            - 2
            - 3
